language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "git config --global github.user travis"
  - "cpanm -n Dist::Zilla::PluginBundle::Author::DOHERTY || curl -F p=@$HOME/.cpanm/build.log http://p.hashbang.ca"
  - "sudo apt-get install libgd2-xpm-dev"
  - "cpanm $( dzil authordeps 2>/dev/null ) || curl -F p=@$HOME/.cpanm/build.log http://p.hashbang.ca"
install: "cpanm $( dzil listdeps 2>/dev/null ) || curl -F p=@$HOME/.cpanm/build.log http://p.hashbang.ca"
script: ".travis.sh"
notifications:
    email:
        recipients:
            - perlwikibot-commits@googlegroups.com
    irc:
        channels:
            - "irc.freenode.org#perlwikibot"
        skip_join: true
    template:
        - "Build %{build_number} on %{branch} (%{commit} by %{author}): %{message} %{build_url}"
