language: perl
before_install:
  - git config --global github.user travis
  - cpanm -n Dist::Zilla::PluginBundle::Author::DOHERTY
  - cpanm -n $( dzil authordeps 2>/dev/null )
script: perl Build.PL && ./Build test && prove -bj4
notifications:
    email:
        recipients:
            - perlwikibot-commits@googlegroups.com
        on_success: "change"
        on_failure: "always"
    irc:
        channels:
            - "irc.freenode.org#perlwikibot"
        skip_join: true
        template:
            - "Build %{build_number} on %{branch} (%{commit} by %{author}): %{message} %{build_url}"
env: AUTHOR_TESTING=1 RELEASE_TESTING=1 AUTOMATED_TESTING=1 EXTENDED_TESTING=1
sudo: false
branches:
    only:
        - master
        - dev
addons:
    apt:
        packages:
            - libgd2-xpm-dev
    artifacts: true
